baseURL = "https://kolya-ya.github.io/edTech-hugo/"
defaultContentLanguage = 'ru'
theme = "aittr-wix"
disableKinds = ["taxonomy", "term"]

[params]
    logoName = "AIT TR"
    email = "go@ait-tr.de"
    phone = "+49 305 201 41 82"
    address = "Linkstraße 2, 10785 Berlin, Germany"
    [params.social]
        [params.social.in]
            name = "LinkedIn"
            link = "https://www.linkedin.com/company/ait-tr/"
            iconName = "linkedin"
        [params.social.fb]
            name = "Facebook"
            link = "https://www.facebook.com/profile.php?id=100085263732597"
            iconName = "facebook"
        [params.social.instagram]
            name = "Instagram"
            link = "https://www.instagram.com/aittr.de/"
            iconName = "instagram"

    

[languages]
    [languages.ru]
        contentDir = "content/ru"
        title = "AIT TR static site"
        headerAnnounces = [
            "Начало обучения 31.10.22",
            "Преподаватели — эксперты из Германии и Израиля",
            "Группы — до 15 человек",
            "6 месяцев обучения",
            "1 месяц разработки проекта",
            "Поможем найти перспективную работу",
        ]
    [languages.en]
        contentDir = 'content/en'
        title = "AIT TR static site"
        headerAnnounces = [
            "The new course will start on the 31.10.2022",
            "The tutors are specialists from Germany and Israel",
            "Groups of up to 15 people",
            "6 months of training",
            "1 month project development",
            "We will help you find a promising job",
        ]
    [languages.de]
        contentDir = 'content/de'
        title = "AIT TR static site"